name: CI Workflow

on:
  push:
    branches:
      - main          # Triggers when changes are pushed to the 'main' branch
      - develop       # Triggers when changes are pushed to the 'develop' branch
      - 'feature/*'   # Triggers when changes are pushed to any branch starting with 'feature/'

  pull_request:
    branches:
      - main          # Triggers when a pull request is made to the 'main' branch
      - develop       # Triggers when a pull request is made to the 'develop' branch
      - 'feature/*'   # Triggers when a pull request is made to any branch starting with 'feature/'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
