name: Notify Moved Files to Webhook

on:
  push:
    branches:
      - Development  # Trigger when changes are pushed to the development branch
    paths:
      - '**/*'  # This means any file in the repository

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get moved or renamed files
      id: get_files
      run: |
        # Get the list of files that were renamed or moved between commits
        files=$(git diff --name-only --diff-filter=R HEAD^..HEAD)  # --diff-filter=R filters for renamed/moved files
        echo "::set-output name=files::$files"

    - name: Send file names to Fusion Webhook
      if: steps.get_files.outputs.files != ''
      run: |
        FILES="${{ steps.get_files.outputs.files }}"
        WEBHOOK_URL="https://hook.app.workfrontfusion.com/9e5xgn2ci4rvv8s0m4whb16d4m3nhu9z"
        
        # Send the files to the webhook
        curl -X POST "$WEBHOOK_URL" \
             -H "Content-Type: application/json" \
             -d "{\"files\": \"$FILES\"}"
