name: My Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello, world!"
