name: My Workflow

on:
  pull_request:
    branches:
      - main  # Trigger on PR creation or updates for main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello, world!"
