name: My Workflow

on:
  push:
    branches:
      - Development  # Trigger on push to development branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello, world!"
